version: '2.1'
orbs:
  node: circleci/node@6.3.0
  docker: circleci/docker@2.8.0
jobs:
  test:
    executor:
      name: node/default
      tag: 'lts'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test

workflows:
  test_my_app:
    jobs:
      - test
      - docker/publish:
          image: 'petez7519/node-addition-service'
          tag: circleci
          context: docker-hub
          docker-username: DOCKER_HUB_USERNAME
          docker-password: DOCKER_HUB_PASSWORD
          requires:
            - test